# Generated by Django 5.0.2 on 2024-03-05 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice_app', '0003_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('c_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('c_password', models.CharField(max_length=50)),
                ('c_name', models.CharField(max_length=50)),
                ('c_email', models.EmailField(max_length=100)),
                ('c_phone', models.CharField(max_length=50)),
                ('c_city', models.CharField(max_length=50)),
                ('c_experience', models.CharField(max_length=100)),
                ('c_qualification', models.CharField(max_length=100)),
                ('c_gender', models.CharField(max_length=10)),
                ('c_skills', models.TextField()),
                ('c_address', models.TextField()),
                ('c_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
