# Generated by Django 5.0.2 on 2024-03-08 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice_app', '0004_counsellor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('st_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('st_password', models.CharField(max_length=50)),
                ('st_name', models.CharField(max_length=50)),
                ('st_email', models.EmailField(max_length=100)),
                ('st_phone', models.CharField(max_length=50)),
                ('st_city', models.CharField(max_length=50)),
                ('st_qualification', models.CharField(max_length=100)),
                ('st_gender', models.CharField(max_length=10)),
                ('st_address', models.TextField()),
                ('st_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
