# Generated by Django 5.0.2 on 2024-03-15 10:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice_app', '0005_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cu_topic', models.CharField(max_length=50)),
                ('cu_content', models.TextField()),
                ('cu_date', models.DateField(default=django.utils.timezone.now)),
                ('counsellor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advice_app.counsellor')),
            ],
        ),
    ]
