# Generated by Django 5.0.2 on 2024-04-04 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice_app', '0006_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_code', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=100)),
                ('college_city', models.CharField(max_length=50)),
                ('college_email', models.EmailField(max_length=100)),
                ('college_phone', models.CharField(max_length=50)),
                ('college_address', models.TextField()),
                ('college_website', models.CharField(max_length=100)),
                ('college_icon', models.FileField(default='', max_length=50, upload_to='advice_app/collegephoto')),
                ('college_rating', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('duration', models.CharField(max_length=50)),
                ('fees', models.CharField(max_length=100)),
                ('about_course', models.TextField()),
                ('career_option', models.TextField()),
                ('eligibility_criteria', models.TextField()),
                ('subjects_offered', models.TextField()),
            ],
        ),
    ]
