# Generated by Django 5.0.2 on 2024-04-15 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice_app', '0008_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('date', models.DateField(max_length=100)),
                ('status', models.CharField(default=False, max_length=50)),
                ('cou_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advice_app.counsellor')),
                ('stu_detail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='advice_app.student')),
            ],
        ),
    ]
