# Generated by Django 5.0.2 on 2024-04-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advice_app', '0009_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
