# Generated by Django 5.0.2 on 2024-05-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice_app', '0011_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='ratings',
            field=models.CharField(max_length=5),
        ),
    ]
